import { FC, ReactNode } from "react";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<IRootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={cn("font-geist-sans", geistSans.variable)}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
